# Generated by Django 4.2.4 on 2023-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes_num',
            field=models.IntegerField(default=0),
        ),
    ]
